lib/adaptics_web/router.ex
defmodule AdapticsWeb.Router do
  use AdapticsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AdapticsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AdapticsWeb do
    pipe_through :browser

    resources "/nodes", NodeController
    resources "/links", LinkController

    get "/ivn", PageController, :nodes
    get "/splines", PageController, :splines
    get "/3d", PageController, :three_d
    get "/voxels", PageController, :voxels
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AdapticsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: AdapticsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/adaptics/visual/node.ex
defmodule Adaptics.Visual.Node do
  use Ecto.Schema
  import Ecto.Changeset

  schema "nodes" do
    field :description, :string
    field :name, :string
    field :hash, :string
    field :kind, :string

    field :wardley_x, :float
    field :wardley_y, :float
    field :z, :float
    field :wardley_text, :string

    timestamps()
  end

  @doc false
  def changeset(node, attrs) do
    node
    |> cast(attrs, [:name, :description, :wardley_x, :wardley_y, :z, :wardley_text])
    |> validate_required([:name, :description])
  end
end

lib/adaptics_web/controllers/node_controller.ex
defmodule AdapticsWeb.NodeController do
  use AdapticsWeb, :controller

  alias Adaptics.Visual
  alias Adaptics.Visual.Node
  import Ecto.Query, warn: false

  def index(conn, _params) do
    nodes = Visual.list_nodes()
    node_count = Adaptics.Repo.one(from p in Adaptics.Visual.Node, select: count("*"))
    render(conn, "index.html", nodes: nodes, node_count: node_count)
  end

  def new(conn, _params) do
    changeset = Visual.change_node(%Node{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"node" => node_params}) do
    case Visual.create_node(node_params) do
      {:ok, node} ->
        conn
        |> put_flash(:info, "Node created successfully.")
        |> redirect(to: Routes.node_path(conn, :show, node))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    node = Visual.get_node!(id)
    hash = node.hash

    links = Adaptics.Repo.all(from u in "links",
          where: u.to_hash == ^hash or u.from_hash == ^hash,
          select: [:id, :to_hash, :from_hash, :name, :description, :from_id, :to_id])

    render(conn, "show.html", node: node, links: links)
  end

  def edit(conn, %{"id" => id}) do
    node = Visual.get_node!(id)
    changeset = Visual.change_node(node)
    render(conn, "edit.html", node: node, changeset: changeset)
  end

  def update(conn, %{"id" => id, "node" => node_params}) do
    node = Visual.get_node!(id)

    case Visual.update_node(node, node_params) do
      {:ok, node} ->
        conn
        |> put_flash(:info, "Node updated successfully.")
        |> redirect(to: Routes.node_path(conn, :show, node))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", node: node, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    node = Visual.get_node!(id)
    {:ok, _node} = Visual.delete_node(node)

    conn
    |> put_flash(:info, "Node deleted successfully.")
    |> redirect(to: Routes.node_path(conn, :index))
  end
end

lib/adaptics_web/views/node_view.ex
defmodule AdapticsWeb.NodeView do
  use AdapticsWeb, :view
end

lib/adaptics_web/templates/node/edit.html.heex
<h1>Edit Node</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.node_path(@conn, :update, @node)) %>

<span><%= link "Back", to: Routes.node_path(@conn, :index) %></span>

lib/adaptics_web/templates/node/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :hash %>
  <%= text_input f, :hash %>
  <%= error_tag f, :hash %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <h3>Wardley fields</h3>

  <%= label f, :wardley_x %>
  <p>
    Genesis 0-25, Internal 26-50, Product 51-74, Commodity 75-100
  </p>
  <%= text_input f, :wardley_x %>
  <%= error_tag f, :wardley_x %>

  <%= label f, :wardley_y %>
  <p>
    Visibility to customer (100), non-visible (0)
  </p>
  <%= text_input f, :wardley_y %>
  <%= error_tag f, :wardley_y %>

  <%= label f, :wardley_text %>
  <%= text_input f, :wardley_text %>
  <%= error_tag f, :wardley_text %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/adaptics_web/templates/node/index.html.heex
<br>
<br>
<h1>
  <%= @node_count %>
  Listing Nodes
</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Hash</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for node <- @nodes do %>
    <tr>
      <td><%= node.name %></td>
      <td><%= node.description %></td>
      <td><%= node.hash %></td>

      <td>
        <span><%= link "Show", to: Routes.node_path(@conn, :show, node) %></span>
        <span><%= link "Edit", to: Routes.node_path(@conn, :edit, node) %></span>
        <span><%= link "Delete", to: Routes.node_path(@conn, :delete, node), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Node", to: Routes.node_path(@conn, :new) %></span>

lib/adaptics_web/templates/node/new.html.heex
<h1>New Node</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.node_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.node_path(@conn, :index) %></span>

lib/adaptics_web/templates/node/show.html.heex
<h1>Show Node</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @node.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @node.description %>
  </li>

  <li>
    <strong>Wardley Y:</strong>
    <%= @node.wardley_y %>
  </li>

  <li>
    <strong>Wardley X:</strong>
    <%= @node.wardley_x %>
  </li>

  <li>
    <strong>Wardley Text:</strong>
    <%= @node.wardley_text %>
  </li>

  <li>
    <strong>Hash:</strong>
    <%= @node.hash %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.node_path(@conn, :edit, @node) %></span> |
<span><%= link "Back", to: Routes.node_path(@conn, :index) %></span>

<br>
<br>
<br>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>From</th>
      <th>To</th>
      <th>From hash</th>
      <th>To hash</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for link <- @links do %>
    <tr>
      <td><%= link.name %></td>
      <td><%= link.description %></td>
      <td><%= link.from_id %></td>
      <td><%= link.to_id %></td>
      <td><%= link.from_hash %></td>
      <td><%= link.to_hash %></td>


    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Link", to: Routes.link_path(@conn, :new) %></span>